-- Supabase/Postgres schema contract for deployed API.
-- Safe to run multiple times.

create extension if not exists pgcrypto;

create table if not exists public.users (
    id            uuid primary key default gen_random_uuid(),
    email         text unique not null,
    hashed_password text not null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz
);

create index if not exists idx_users_email
on public.users (email);

create table if not exists public.user_profiles (
    user_id text primary key,
    profile jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.products (
    product_id        integer primary key,
    product_name      text not null,
    brand             text,
    category          text,
    price             numeric(10, 2),
    image_url         text,
    ingredients       text[],
    short_description text,
    created_at        timestamptz not null default now()
);

create index if not exists idx_products_category
on public.products (category);

create index if not exists idx_products_brand
on public.products (brand);

create index if not exists idx_products_price
on public.products (price);

create table if not exists public.product_dupes (
    id                     bigint generated by default as identity primary key,
    source_product_id      integer not null references public.products(product_id),
    dupe_product_id        integer not null references public.products(product_id),
    dupe_score             float not null,
    cosine_sim             float not null,
    price_score            float not null,
    ingredient_group_score float not null,
    explanation            text,
    created_at             timestamptz not null default now(),
    unique(source_product_id, dupe_product_id)
);

create index if not exists idx_product_dupes_source
on public.product_dupes (source_product_id);

create table if not exists public.user_product_events (
    id                    bigint generated by default as identity primary key,
    user_id               uuid not null references public.users(id) on delete cascade,
    product_id            integer not null references public.products(product_id),
    event_type            text not null,
    reaction              text,
    reason_tags           jsonb not null default '[]'::jsonb,
    free_text             text,
    has_tried             boolean not null default false,
    skipped_questionnaire boolean not null default false,
    created_at            timestamptz not null default now()
);

create index if not exists idx_events_user
on public.user_product_events (user_id);

create index if not exists idx_events_product
on public.user_product_events (product_id);

create index if not exists idx_events_user_time
on public.user_product_events (user_id, created_at desc);

create index if not exists idx_events_type
on public.user_product_events (event_type);

create table if not exists public.user_model_state (
    user_id            uuid primary key references public.users(id) on delete cascade,
    interactions       int not null default 0,
    liked_count        int not null default 0,
    disliked_count     int not null default 0,
    irritation_count   int not null default 0,
    liked_reasons      jsonb not null default '[]'::jsonb,
    disliked_reasons   jsonb not null default '[]'::jsonb,
    irritation_reasons jsonb not null default '[]'::jsonb,
    updated_at         timestamptz not null default now()
);

create table if not exists public.recommendation_log (
    id            bigint generated by default as identity primary key,
    user_id       uuid not null references public.users(id) on delete cascade,
    product_id    integer not null references public.products(product_id),
    session_id    uuid,
    model_used    text,
    rank_position int,
    score         float,
    created_at    timestamptz not null default now()
);

create index if not exists idx_rec_log_user
on public.recommendation_log (user_id);

create index if not exists idx_rec_log_session
on public.recommendation_log (session_id);

create index if not exists idx_rec_log_user_time
on public.recommendation_log (user_id, created_at desc);

create table if not exists public.user_wishlists (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references public.users(id) on delete cascade,
    product_id  integer not null references public.products(product_id),
    created_at  timestamptz not null default now(),
    unique(user_id, product_id)
);

create index if not exists idx_wishlist_user
on public.user_wishlists (user_id);

create table if not exists public.chat_messages (
    id         bigint generated by default as identity primary key,
    user_id    uuid references public.users(id) on delete set null,
    role       text not null,
    content    text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_chat_user
on public.chat_messages (user_id);

create index if not exists idx_chat_user_time
on public.chat_messages (user_id, created_at asc);

create table if not exists public.model_checkpoints (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references public.users(id) on delete cascade,
    model_type  text not null,
    model_blob  bytea,
    n_updates   int not null default 0,
    created_at  timestamptz not null default now()
);

create index if not exists idx_model_checkpoints_user
on public.model_checkpoints (user_id);

create index if not exists idx_model_checkpoints_user_type
on public.model_checkpoints (user_id, model_type);
