-- Supabase/Postgres migration for API user persistence state
-- Safe to run multiple times.

create table if not exists public.user_profiles (
    user_id text primary key,
    profile jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.user_feedback_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    product_id integer not null,
    has_tried boolean not null,
    reaction text,
    reason_tags jsonb not null default '[]'::jsonb,
    free_text text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_user_feedback_events_user_id
    on public.user_feedback_events (user_id);

create index if not exists idx_user_feedback_events_created_at
    on public.user_feedback_events (created_at desc);

create index if not exists idx_user_feedback_events_user_created
    on public.user_feedback_events (user_id, created_at desc);
