FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY setup.py /app/
COPY skincarelib /app/skincarelib
COPY deployment /app/deployment

RUN python -m pip install --upgrade pip \
    && pip install -e .[api]

EXPOSE 8000
CMD ["uvicorn", "deployment.api:app", "--host", "0.0.0.0", "--port", "8000"]
